# Generated by Django 4.2.7 on 2023-11-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('floor', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('reserved', 'reserved'), ('sold', 'sold'), ('installment', 'installment'), ('barter', 'barter')], max_length=20)),
                ('price', models.FloatField()),
                ('building', models.CharField(choices=[('Prime City', 'Prime City'), ('Kochmon', 'Kochmon'), ('Baytik', 'Baytik'), ('Magic City', 'Magic City')], max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
        ),
    ]
