# Generated by Django 3.2.5 on 2023-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('reserved', 'reserved'), ('sold', 'sold'), ('installment', 'installment'), ('barter', 'barter')], default='active', max_length=20),
        ),
    ]
